export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function PatientLayout({ children }) {
  return (
    <>
      <main>{children}</main>
    </>);
}