import Navbar from '@/components/Navbar'
import { createClient } from '@/lib/supabase/server'

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default async function ProtectedLayout({ children }) {
  const supabase = await createClient()

  // 1. Get the authenticated user
  const { data: { user } } = await supabase.auth.getUser()

  let role = 'patient'
  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profile?.role) {
      role = profile.role
    }
  }
  return (
    <>
      <Navbar role={role} userEmail={user?.email} />
      <main className="pt-16">{children}</main>
    </>
  );
}
